### ISSUE TITLE
`npm run setup` fails with error: "No such file or directory"

### ISSUE THREAD

**Issue by charlieblevins** [solid/solidos#106]
The source of the issue is the [asterisk here](https://github.com/solid/solidos/commit/4bd6c0316e42ba8d7c7719af4f7cd851ab25d13a#r62523904). Do we know why this was added or if it can be removed?

**Comment by theRealImy** [comment]
I have same issue. 
My error `scripts/add: line 1: *#!/bin/bash: No such file or directory`

**Comment by bourgeoa** [comment]
Should be resolved with https://github.com/solid/solidos/commit/6bd263af1f3d923353307da48af94d4b0f25964e
