### ISSUE TITLE
streamline CI

### ISSUE THREAD

**Issue by bourgeoa** [solid/solidos#116]
### CI situation 2022-01-30

| repo       | webpack  | node       | other steps      | npm publish            | dependencies |
|----------|----|------------|------------------|------------------------|--------------|
| rdflib |v4      | 12, 14, 16 | save 14, gh-pages| build, latest |
| solid-logic  || 12, 14, 16 |                  |                        | rdflib |
| pane-registry|| 10, 12, 14, 15 |              |                        | rdflib, solid-logic |
| solid-ui | v4   | 12, 14, 15  | save 14, gh-pages | build, latest         | rdflib, solid-logic, pane-registry |
| activitystreams-pane| v4 | no CI         |             |                    | rdflib, solid-logic, pane-registry, solid-ui |
| chat-pane    | v4       | no CI         |             |                    | rdflib, solid-ui |
| contacts-pane    |   | 12, 14, 15    |  save 14 | broken: build, latest | rdflib, pane-registry, solid-ui |
| folder-pane     |    | no CI         |             |                    |rdflib, solid-ui
| issue-pane       |   | 12, 14, 16    |             |                   | rdflib, pane-registry, solid-ui |
| meeting-pane   | v4     | no CI         |             |                   | rdflib, solid-ui
| profile-pane   | v5     | 12, 14, 15    | save 14     | broken: build, latest | contacts-pane, rdflib, solid-logic, pane-registry, solid-ui
| source-pane   |      | no CI         |             |                                | solid-ui |
| solid-panes | v5 |12,14,16    |         |             |                                | all above |
| mashlib    | v4  |10,12,14,15 | save 14, gh-pages         | build             | rdflib, solid-ui, solid-panes |
||
| NSS    |       | 12, 14|test-suite on 12, 14       | docker-hub  latest | rdflib, mashlib |
|deprecated|
|markdown|    |   14, 16    | save 14     |  build latest |   rdflib, solid-ui, pane-registry |

build means : npm publish version+commit
latest means : npm publish version latest

### comments :
	- why ? rdflib in individual panes except source-pane
	- why ? pane-registry in activitystreams, contacts, issue and profile pane
	- todo webpack 4 --> 5

**Comment by theRealImy** [comment]
I am working to make all repos have a running similar CI that is triggered on push and PR on all branchs.
- [ ] solid-logic
- [ ] solid-ui
- [ ] pane-registry 
- [ ] activitystreams-pane
- [ ] chat-pane 
- [ ] contacts-pane
- [ ] folder-pane 
- [ ] issue-pane 
- [ ] meeting-pane 
- [ ] profile-pane
- [ ] source-pane 
- [ ] solid-panes
- [ ] mashlib 
- [ ] NSS

**Comment by theRealImy** [comment]
I am not sure, but for now we have differences in how repos are being build. For example: I need to skip lint on oslid-logic because it has on purpose some errors to fix typescript...

**Comment by bourgeoa** [comment]
Interesting. In purpose ?

**Comment by theRealImy** [comment]
What I meant to say :)  is: in solid-logic in the authSession file we have // @ts-ignore lines on the code to avoid ts problems but it causes lint errors. The code needs to be improved longterm but I just do nto know how. The exact location is now: https://github.com/solid/solid-ui/blob/eb82ec38b28b2e2feb872492149f48b6507ebf42/src/authn/authSession.ts#L7 ( this is moved to solid-logic soon)
