### ISSUE TITLE
Add solid-logic and pane-registry to reset script and to readme

### ISSUE THREAD

**Issue by theRealImy** [solid/solidos#131]
solid-logic and pane-registry are the only subrepos not pulled in when building solidos.

**Comment by bourgeoa** [comment]
Well no a lot of panes are also missing.

**Comment by theRealImy** [comment]
> Well no a lot of panes are also missing.

@bourgeoa true but those are central like these ones.

**Comment by bourgeoa** [comment]
> solid-logic and pane-registry are the only subrepos not pulled in when building solidos.

True ☺️ I was kindly joking

**Comment by theRealImy** [comment]
@bourgeoa please review the new scripts: https://github.com/solid/solidos/pull/132
