### ISSUE TITLE
`npm run prepare` missing

### ISSUE THREAD

**Issue by joeitu** [solid/solidos#145]
Hello, 

When following https://github.com/solid/solidos#solidos-first-time-setup-of-code 
`npm run prepare` seems to be missing from the package.json

**Comment by bourgeoa** [comment]
Thanks. You are right. It has been removed recently since all solidOS is now tested and build on node 16.14.0
May be we should have kept it for clarity. I haven't checked the documentation.

**Comment by theRealImy** [comment]
Hi @joeitu -> we will update the documentation thank you. Basically, that script is not needed anymore. Everything should run with node 14 and 16. (locally it is set up with node 16.14.0)
