### ISSUE TITLE
Error: Account recovery email has not been provided, but it has

### ISSUE THREAD

**Issue by sideshowtom** [solid/solidos#26]
I get an error
Error: Account recovery email has not been provided
when trying to delete my pod,
but the preferences has an mbox entry with email address.

**Comment by bourgeoa** [comment]
The email address used to delete your pod is the one that you provided at pod creation.

**Comment by sideshowtom** [comment]
Thanks.  Yes, that's the same one in the preferences file, but I still get the error and no email.

**Comment by bourgeoa** [comment]
I just tried to delete my pod https://bourgeoa.inrupt.net and received the email with the link to confirm deletion of the pod.
> Error: Account recovery email has not been provided

this message means that you did not provide an email when you created your pod.
The email cannot be added after nor changed, he is stored as an index key in the keys database.
Only a pod provider admin at https://inrupt.net can delete your pod.

**Comment by sideshowtom** [comment]
Ok thanks.  How do I contact an admin at inrupt.net to do that?

**Comment by bourgeoa** [comment]
I don't know you can try a message in the chat canal `https://gitter.im/solid/chat` or solid/node-solid-server.
I am an admin on `solidcommunity.net`

**Comment by sideshowtom** [comment]
The drift I get from there is that I should stay at http://127.0.0.1

**Comment by bourgeoa** [comment]
You can use `https://solidcommunity.net`
Which also has support at `https://github.com/solid/solidcommunity.net`

**Comment by sideshowtom** [comment]
👍 Thanks @bourgeoa !

**Comment by angelo-v** [comment]
So we can close this here, I guess?

**Comment by sideshowtom** [comment]
I would say no, it shouldn’t be closed, because moving to another pod provider might be ok, but  leaving my pod (I still have the password, so I *did* create it) and it’s data there is not good, and having to plead for resolution on a chat channel is worse.

**Comment by angelo-v** [comment]
Then I do not yet understand what needs to be done on SolidOS. If you want a feature to add a recovery email, I second that, but let's do a seperate issue with as feature request, so one does not have to dig it out of this thread

**Comment by sideshowtom** [comment]
Maybe this issue should be moved, but it is still a bug.  You should be able to add a recovery email if you have the password and you forgot to add it on creation.  Maybe an alternative is not to allow pod creation without a verified recovery email.
