### ISSUE TITLE
How to report possible issue/misconfiguration in solidos.solidcommunity.net ?

### ISSUE THREAD

**Issue by macedogm** [solid/solidos#34]
Hi! 👋🏻
What is the best way to report a possible issue or misconfiguration in [solidos.solidcommunity.net](https://solidos.solidcommunity.net/), please? Is there an email address that I can send to?
Since I don't know if it's really an issue or just intentional, I prefer not to report directly here without prior authorisation.

**Comment by bourgeoa** [comment]
You can post your questions in the chat channel https://gitter.im/solidos or on the forum https://forum.solidproject.org/

No authorization needed. The github is mostly for reporting issues.

**Comment by macedogm** [comment]
Thank you @bourgeoa .
I'll ask/report this in https://forum.solidproject.org .
