### ISSUE TITLE
Auth-Upgrade does not completely logout of NSS

### ISSUE THREAD

**Issue by jeff-zucker** [solid/solidos#56]
Using a web browser to go directly to login in to solidcommunity.net:8443 and then logout leaves the user in a mixed state where the UI looks like they are logged out and they can not create new or delete existing resources.  However, they can still see read, edit, and save resources that require login.

**Comment by jeff-zucker** [comment]
Logged out users can also modify the sharing of all resources.

**Comment by SharonStrats** [comment]
@jeff-zucker I'm having trouble reproducing.  On my machine a local instance of solidos. I have the auth-upgrade branch of solid-ui, solid-panes, mashlib, node-solid-server, and solid-logic.  

I went into my private folder and created a new con

![](https://files.gitter.im/5ee917dbd73408ce4fe71415/Y9nv/Screen-Shot-2021-09-18-at-10.42.28-am.png)
tact group and two contacts. I made sure my acl (sharing) is set to private.  When I click on logout I get this following message right away.

**Comment by jeff-zucker** [comment]
Please try with the source pane or folder pane which is where I get the errors.  The panes all act differently, showing it works in one pane does not prove it works in others.

**Comment by jeff-zucker** [comment]
Also please try against solidcommunity.net:8443 so we know we are all working against the same source.

**Comment by jeff-zucker** [comment]
I can confirm - contacts pane logs out correctly for me but source and folder still do not.

**Comment by jeff-zucker** [comment]
I can also confirm, that although contacts pane looks like it is logged out, shows a login button, I can still modify the sharing of the address book itself

**Comment by jeff-zucker** [comment]
For me  the following panes do not logout : rdf, about, markdown, source, folder, sharing.  I haven't tested all the app panes.

**Comment by jeff-zucker** [comment]
I believe this has been solved with Jackson's changes to NSS in 5.6.9 beta.
