### ISSUE TITLE
First time setup fails

### ISSUE THREAD

**Issue by angelo-v** [solid/solidos#6]
I tried initial setup and am getting:

```scripts/add: Line 117: cd: workspaces: File or directory not found```

What should have created the workspaces directory?

@michielbdejong

**Comment by michielbdejong** [comment]
Ah sorry I must have accidentally deleted workspaces/.gitkeep

**Comment by angelo-v** [comment]
fixed in https://github.com/solid/solidos/pull/7

**Comment by michielbdejong** [comment]
Can this be closed?
