### ISSUE TITLE
auth-upgrade : check npm-update dependencies

### ISSUE THREAD

**Issue by bourgeoa** [solid/solidos#69]
Before publishing the solidos full stack from main a review of the dependencies would make publishing easier.

The process of publishing is done with https://github.com/solid/solidos/blob/main/scripts/release
- There is a step to update dependencies `npx npm-check-updates -u`
- without -u you are displayed with a list
- each repo in order see his dependencies updated and revert some dependencies to older ones

example webpack@4 and webpack-cli@3
For example a new rule must apply to eslint because eslint@8 is not compatible with node.js < 16. I feel we should not accept that it seems quite early

**Comment by theRealImy** [comment]
@bourgeoa managed to update solid-ui as mentioned privately. See PR above. 
This means the release script must be updated accordingly for solid-ui. Solid-ui does not need any more 
`npm install --save-dev webpack@4
npm install --save-dev webpack-cli@3`

**Comment by theRealImy** [comment]
Done.
