### ISSUE TITLE
Webapp does not display storage(s)

### ISSUE THREAD

**Issue by jeff-zucker** [solid/solidos#86]
The new storage improvements are not available in the web app. Neither the storage button nor the menu appear.

![alain1](https://user-images.githubusercontent.com/44732708/140526404-a0586dd6-b4ca-4238-84dd-1b2d452a2c93.png)
.

**Comment by jeff-zucker** [comment]
Please note : previous to this release (the one currently on :8443) there was a storage button but no menu.  The menu we can consider an enhancement and add later, but the disappearance of the storage button and no way to see the multiple storages is a problem.

**Comment by jeff-zucker** [comment]
I have done some more testing, here's my notes (abbreviating solidcommunity.net as scn)
                                                                             
Using local browse.html from **either** mashlib 1.78 or 1.79                                    
                                                                             
* These both show all four dashboard tabs including "Your storage"           
  * login as me@scn:8443 at me@scn:8843                                      
  * login as me@scn at me@scn                                                
* These show "bourgeoa@scn:8443's pod" and no dashboard tabs                 
  * login as anything at bourgeoa.scn:8443/     
 
I get identical behavior from 1.79 so if one of these is without the storage changes, that probably means it is not a new bug. So I suggest we change this to an enhancement and release.

**Comment by jeff-zucker** [comment]
It's possible that running it local gives different results so it might be useful to have a browse.html available on the test server.

**Comment by bourgeoa** [comment]
@jeff-zucker I found a situation where it works correctly.
Both solidcommunity.net:8443 and solidweb.org are running NSS@5.6.14 with mashlib@1.7.8
![image](https://user-images.githubusercontent.com/2218470/140585575-b2d72ce4-05bf-44fd-b517-1c00609081eb.png)

**Comment by jeff-zucker** [comment]
Wow, that is really odd from several points of view.  First, why would it work there and no where else?  Second - why does it show you as visiting and logged in at solidweb but with a storage from solidcommunity,net?  What sequence did you follow?  

Also please clarify - 1.7.9 is the latest or it the previous that you reverted to and 1.7.8 is actually newer?

**Comment by jeff-zucker** [comment]
I can not reproduce your results, this is with a browse.html on :8443 visiting solidweb.org and logging in on :8443 from there.

**Comment by jeff-zucker** [comment]
![alain2](https://user-images.githubusercontent.com/44732708/140613373-4058bed5-5623-4f14-84a0-2ffe698020aa.png)

**Comment by bourgeoa** [comment]
@jeff-zucker I think issue resolved. The error was cannot load container.
replaced : 
```        await addPodRootFromUrl(window.location.href)
```
by : 
```        await addPodRootFromUrl(window.location.href.substring(0, window.location.href.lastIndexOf('/') + 1))
```

solidcommunity.net is running with mashlib@1.7.7
and for the time being solidcommunity.net:8443 is running mashlib@1.7.9

mashlib@1.7.8 was wrong and never used in NSS. It is not possible to remove version from npmjs

**Comment by jeff-zucker** [comment]
When you say resolved, do you mean there is a working version somewhere that I can test?  Where?

**Comment by bourgeoa** [comment]
It will come I tested locally. Shall install on test-server soon.

**Comment by jeff-zucker** [comment]
OH, I see, good spotting!  This is exactly the same problem with the IDP dropdown in https://github.com/solid/solidos/issues/88!

**Comment by bourgeoa** [comment]
Solved with https://github.com/solid/solid-panes/pull/311

**Comment by bourgeoa** [comment]
1. As can be seen below dashboard-pane is only displayed when webId and search uri have same origin.
There is no regression anymore. But this seem an existing bug. Opened #89 

| url | search uri | webId | solidcommunity.net | solidcommunity.net:8443 |
|----|---------|-------------|-----------------------|------------------------------|
bou | bou1 | no-webId | default | default |
bou | bou1 | bou-Id | default | default |
bou | bou | bou-Id | dashboard | dashboard |
bou | bou1 | bou-Id | default | default |
bou | bou1 | bou1-Id | dashboard | dashboard |
bou1 | bou | no-webId | default | default |
bou1 | bou | bou1-Id | default | default |
bou1 | bou1 | bou1-Id | dashboard | dashboard |
bou1 | bou | bou-Id | dashboard | dashboard |

bou : https://bourgeoa.solidcommunity.net/ or https://bourgeoa.solidcommunity.net:8443/
bou1 : https://bourgeoa1.solidcommunity.net/ or https://bourgeoa1.solidcommunity.net:8443/
url : bou/brows.html or bou1/browse.html
bou-Id : bou/profile/card#me
bou1-Id : bou1/profile/card#me

2. a problem occured when using an url that is not on a solid server (https://github.io). Issue found shall be resolved too in mashlib > 1.7.10

**Comment by bourgeoa** [comment]
solved with https://github.com/solid/solid-panes/pull/312
